//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.11 at 06:59:59 PM EEST 
//


package bg.registryagency.schemas.deedv2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bg.registryagency.schemas.deedv2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Deed_QNAME = new QName("http://www.registryagency.bg/schemas/deedv2", "Deed");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bg.registryagency.schemas.deedv2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IncomingPackageInfoType }
     * 
     */
    public IncomingPackageInfoType createIncomingPackageInfoType() {
        return new IncomingPackageInfoType();
    }

    /**
     * Create an instance of {@link DeedType }
     * 
     */
    public DeedType createDeedType() {
        return new DeedType();
    }

    /**
     * Create an instance of {@link DocumentType }
     * 
     */
    public DocumentType createDocumentType() {
        return new DocumentType();
    }

    /**
     * Create an instance of {@link SubDeedType }
     * 
     */
    public SubDeedType createSubDeedType() {
        return new SubDeedType();
    }

    /**
     * Create an instance of {@link IncomingPackageInfoType.Documents }
     * 
     */
    public IncomingPackageInfoType.Documents createIncomingPackageInfoTypeDocuments() {
        return new IncomingPackageInfoType.Documents();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.registryagency.bg/schemas/deedv2", name = "Deed")
    public JAXBElement<DeedType> createDeed(DeedType value) {
        return new JAXBElement<DeedType>(_Deed_QNAME, DeedType.class, null, value);
    }

}
