//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.11 at 06:59:59 PM EEST 
//


package bg.registryagency.schemas.deedv2.fields;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InsolvencyOfForeignTrader" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{http://www.registryagency.bg/schemas/deedv2/Fields}RecordCommonAttributes"/>
 *                 &lt;attribute name="InsolvencyText" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ActNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ActDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="JudicialCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Decision759" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Decision760" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.registryagency.bg/schemas/deedv2/Fields}FieldCommonAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "insolvencyOfForeignTrader"
})
@XmlRootElement(name = "InsolvenciesOfForeignTrader")
public class InsolvenciesOfForeignTrader {

    @XmlElement(name = "InsolvencyOfForeignTrader")
    protected List<InsolvenciesOfForeignTrader.InsolvencyOfForeignTrader> insolvencyOfForeignTrader;
    @XmlAttribute(name = "FieldIdent", required = true)
    protected String fieldIdent;
    @XmlAttribute(name = "FieldOperation", required = true)
    protected FieldOperation fieldOperation;
    @XmlAttribute(name = "FieldEntryNumber", required = true)
    protected String fieldEntryNumber;
    @XmlAttribute(name = "FieldActionDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fieldActionDate;

    /**
     * Gets the value of the insolvencyOfForeignTrader property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the insolvencyOfForeignTrader property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInsolvencyOfForeignTrader().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InsolvenciesOfForeignTrader.InsolvencyOfForeignTrader }
     * 
     * 
     */
    public List<InsolvenciesOfForeignTrader.InsolvencyOfForeignTrader> getInsolvencyOfForeignTrader() {
        if (insolvencyOfForeignTrader == null) {
            insolvencyOfForeignTrader = new ArrayList<InsolvenciesOfForeignTrader.InsolvencyOfForeignTrader>();
        }
        return this.insolvencyOfForeignTrader;
    }

    /**
     * Gets the value of the fieldIdent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldIdent() {
        return fieldIdent;
    }

    /**
     * Sets the value of the fieldIdent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldIdent(String value) {
        this.fieldIdent = value;
    }

    /**
     * Gets the value of the fieldOperation property.
     * 
     * @return
     *     possible object is
     *     {@link FieldOperation }
     *     
     */
    public FieldOperation getFieldOperation() {
        return fieldOperation;
    }

    /**
     * Sets the value of the fieldOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldOperation }
     *     
     */
    public void setFieldOperation(FieldOperation value) {
        this.fieldOperation = value;
    }

    /**
     * Gets the value of the fieldEntryNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldEntryNumber() {
        return fieldEntryNumber;
    }

    /**
     * Sets the value of the fieldEntryNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldEntryNumber(String value) {
        this.fieldEntryNumber = value;
    }

    /**
     * Gets the value of the fieldActionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFieldActionDate() {
        return fieldActionDate;
    }

    /**
     * Sets the value of the fieldActionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFieldActionDate(XMLGregorianCalendar value) {
        this.fieldActionDate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{http://www.registryagency.bg/schemas/deedv2/Fields}RecordCommonAttributes"/>
     *       &lt;attribute name="InsolvencyText" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ActNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ActDate" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="JudicialCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Decision759" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Decision760" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class InsolvencyOfForeignTrader {

        @XmlAttribute(name = "InsolvencyText")
        protected String insolvencyText;
        @XmlAttribute(name = "ActNumber")
        protected String actNumber;
        @XmlAttribute(name = "ActDate")
        protected String actDate;
        @XmlAttribute(name = "JudicialCode")
        protected String judicialCode;
        @XmlAttribute(name = "Decision759")
        protected String decision759;
        @XmlAttribute(name = "Decision760")
        protected String decision760;
        @XmlAttribute(name = "RecordID", required = true)
        protected int recordID;
        @XmlAttribute(name = "GroupID", required = true)
        protected int groupID;
        @XmlAttribute(name = "RecordIncomingNumber", required = true)
        protected String recordIncomingNumber;

        /**
         * Gets the value of the insolvencyText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInsolvencyText() {
            return insolvencyText;
        }

        /**
         * Sets the value of the insolvencyText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInsolvencyText(String value) {
            this.insolvencyText = value;
        }

        /**
         * Gets the value of the actNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActNumber() {
            return actNumber;
        }

        /**
         * Sets the value of the actNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActNumber(String value) {
            this.actNumber = value;
        }

        /**
         * Gets the value of the actDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActDate() {
            return actDate;
        }

        /**
         * Sets the value of the actDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActDate(String value) {
            this.actDate = value;
        }

        /**
         * Gets the value of the judicialCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJudicialCode() {
            return judicialCode;
        }

        /**
         * Sets the value of the judicialCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJudicialCode(String value) {
            this.judicialCode = value;
        }

        /**
         * Gets the value of the decision759 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDecision759() {
            return decision759;
        }

        /**
         * Sets the value of the decision759 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDecision759(String value) {
            this.decision759 = value;
        }

        /**
         * Gets the value of the decision760 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDecision760() {
            return decision760;
        }

        /**
         * Sets the value of the decision760 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDecision760(String value) {
            this.decision760 = value;
        }

        /**
         * Gets the value of the recordID property.
         * 
         */
        public int getRecordID() {
            return recordID;
        }

        /**
         * Sets the value of the recordID property.
         * 
         */
        public void setRecordID(int value) {
            this.recordID = value;
        }

        /**
         * Gets the value of the groupID property.
         * 
         */
        public int getGroupID() {
            return groupID;
        }

        /**
         * Sets the value of the groupID property.
         * 
         */
        public void setGroupID(int value) {
            this.groupID = value;
        }

        /**
         * Gets the value of the recordIncomingNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordIncomingNumber() {
            return recordIncomingNumber;
        }

        /**
         * Sets the value of the recordIncomingNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordIncomingNumber(String value) {
            this.recordIncomingNumber = value;
        }

    }

}
