//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.11 at 06:59:59 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.registryagency.bg/schemas/deedv2/Fields", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bg.registryagency.schemas.deedv2.fields;
