//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.11 at 06:59:59 PM EEST 
//


package bg.registryagency.schemas.deedv2.fields;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.registryagency.bg/schemas/deedv2/Fields}RecordCommonAttributes"/>
 *       &lt;attGroup ref="{http://www.registryagency.bg/schemas/deedv2/Fields}FieldCommonAttributes"/>
 *       &lt;attribute name="fromacquisition" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="frommerge" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fromholding" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fromsubsidiary" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fromconvert" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "WayOfEstablishingEuropeanCompany")
public class WayOfEstablishingEuropeanCompany {

    @XmlAttribute(name = "fromacquisition")
    protected String fromacquisition;
    @XmlAttribute(name = "frommerge")
    protected String frommerge;
    @XmlAttribute(name = "fromholding")
    protected String fromholding;
    @XmlAttribute(name = "fromsubsidiary")
    protected String fromsubsidiary;
    @XmlAttribute(name = "fromconvert")
    protected String fromconvert;
    @XmlAttribute(name = "RecordID", required = true)
    protected int recordID;
    @XmlAttribute(name = "GroupID", required = true)
    protected int groupID;
    @XmlAttribute(name = "RecordIncomingNumber", required = true)
    protected String recordIncomingNumber;
    @XmlAttribute(name = "FieldIdent", required = true)
    protected String fieldIdent;
    @XmlAttribute(name = "FieldOperation", required = true)
    protected FieldOperation fieldOperation;
    @XmlAttribute(name = "FieldEntryNumber", required = true)
    protected String fieldEntryNumber;
    @XmlAttribute(name = "FieldActionDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fieldActionDate;

    /**
     * Gets the value of the fromacquisition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromacquisition() {
        return fromacquisition;
    }

    /**
     * Sets the value of the fromacquisition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromacquisition(String value) {
        this.fromacquisition = value;
    }

    /**
     * Gets the value of the frommerge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrommerge() {
        return frommerge;
    }

    /**
     * Sets the value of the frommerge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrommerge(String value) {
        this.frommerge = value;
    }

    /**
     * Gets the value of the fromholding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromholding() {
        return fromholding;
    }

    /**
     * Sets the value of the fromholding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromholding(String value) {
        this.fromholding = value;
    }

    /**
     * Gets the value of the fromsubsidiary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromsubsidiary() {
        return fromsubsidiary;
    }

    /**
     * Sets the value of the fromsubsidiary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromsubsidiary(String value) {
        this.fromsubsidiary = value;
    }

    /**
     * Gets the value of the fromconvert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromconvert() {
        return fromconvert;
    }

    /**
     * Sets the value of the fromconvert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromconvert(String value) {
        this.fromconvert = value;
    }

    /**
     * Gets the value of the recordID property.
     * 
     */
    public int getRecordID() {
        return recordID;
    }

    /**
     * Sets the value of the recordID property.
     * 
     */
    public void setRecordID(int value) {
        this.recordID = value;
    }

    /**
     * Gets the value of the groupID property.
     * 
     */
    public int getGroupID() {
        return groupID;
    }

    /**
     * Sets the value of the groupID property.
     * 
     */
    public void setGroupID(int value) {
        this.groupID = value;
    }

    /**
     * Gets the value of the recordIncomingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordIncomingNumber() {
        return recordIncomingNumber;
    }

    /**
     * Sets the value of the recordIncomingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordIncomingNumber(String value) {
        this.recordIncomingNumber = value;
    }

    /**
     * Gets the value of the fieldIdent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldIdent() {
        return fieldIdent;
    }

    /**
     * Sets the value of the fieldIdent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldIdent(String value) {
        this.fieldIdent = value;
    }

    /**
     * Gets the value of the fieldOperation property.
     * 
     * @return
     *     possible object is
     *     {@link FieldOperation }
     *     
     */
    public FieldOperation getFieldOperation() {
        return fieldOperation;
    }

    /**
     * Sets the value of the fieldOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldOperation }
     *     
     */
    public void setFieldOperation(FieldOperation value) {
        this.fieldOperation = value;
    }

    /**
     * Gets the value of the fieldEntryNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldEntryNumber() {
        return fieldEntryNumber;
    }

    /**
     * Sets the value of the fieldEntryNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldEntryNumber(String value) {
        this.fieldEntryNumber = value;
    }

    /**
     * Gets the value of the fieldActionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFieldActionDate() {
        return fieldActionDate;
    }

    /**
     * Sets the value of the fieldActionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFieldActionDate(XMLGregorianCalendar value) {
        this.fieldActionDate = value;
    }

}
