//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.11 at 06:59:59 PM EEST 
//


package bg.registryagency.schemas.envelopev2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SearchCriteriaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SearchCriteriaType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SearchByUic"/>
 *     &lt;enumeration value="SeatchForRights"/>
 *     &lt;enumeration value="SearchForDeeds"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SearchCriteriaType")
@XmlEnum
public enum SearchCriteriaType {

    @XmlEnumValue("SearchByUic")
    SEARCH_BY_UIC("SearchByUic"),
    @XmlEnumValue("SeatchForRights")
    SEATCH_FOR_RIGHTS("SeatchForRights"),
    @XmlEnumValue("SearchForDeeds")
    SEARCH_FOR_DEEDS("SearchForDeeds");
    private final String value;

    SearchCriteriaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SearchCriteriaType fromValue(String v) {
        for (SearchCriteriaType c: SearchCriteriaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
