//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.11 at 06:59:59 PM EEST 
//


package bg.registryagency.schemas.envelopev2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import bg.registryagency.schemas.deedv2.DeedStatusType;


/**
 * <p>Java class for SearchCriteria complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchCriteria">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SearchType" type="{http://www.registryagency.bg/schemas/envelopev2}SearchCriteriaType"/>
 *         &lt;element name="Uic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CompanyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="FieldIdentities" type="{http://www.registryagency.bg/schemas/envelopev2}ArrayOfString" minOccurs="0"/>
 *         &lt;element name="SearchInHistory" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="DeedStatus" type="{http://www.registryagency.bg/schemas/deedv2}DeedStatusType"/>
 *         &lt;element name="SearchForDeedsType" type="{http://www.registryagency.bg/schemas/envelopev2}SearchForDeedsType"/>
 *         &lt;element name="LegalForm" type="{http://www.registryagency.bg/schemas/deedv2}LegalFormType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchCriteria", propOrder = {
    "searchType",
    "uic",
    "companyName",
    "startDate",
    "endDate",
    "fieldIdentities",
    "searchInHistory",
    "deedStatus",
    "searchForDeedsType",
    "legalForm"
})
public class SearchCriteria {

    @XmlElement(name = "SearchType", required = true)
    @XmlSchemaType(name = "string")
    protected SearchCriteriaType searchType;
    @XmlElement(name = "Uic")
    protected String uic;
    @XmlElement(name = "CompanyName")
    protected String companyName;
    @XmlElement(name = "StartDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "EndDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDate;
    @XmlElement(name = "FieldIdentities")
    protected ArrayOfString fieldIdentities;
    @XmlElement(name = "SearchInHistory")
    protected boolean searchInHistory;
    @XmlElement(name = "DeedStatus", required = true, nillable = true)
    @XmlSchemaType(name = "string")
    protected DeedStatusType deedStatus;
    @XmlElement(name = "SearchForDeedsType", required = true, nillable = true)
    @XmlSchemaType(name = "string")
    protected SearchForDeedsType searchForDeedsType;
    @XmlElement(name = "LegalForm", required = true, nillable = true)
    protected String legalForm;

    /**
     * Gets the value of the searchType property.
     * 
     * @return
     *     possible object is
     *     {@link SearchCriteriaType }
     *     
     */
    public SearchCriteriaType getSearchType() {
        return searchType;
    }

    /**
     * Sets the value of the searchType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchCriteriaType }
     *     
     */
    public void setSearchType(SearchCriteriaType value) {
        this.searchType = value;
    }

    /**
     * Gets the value of the uic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUic() {
        return uic;
    }

    /**
     * Sets the value of the uic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUic(String value) {
        this.uic = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the fieldIdentities property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getFieldIdentities() {
        return fieldIdentities;
    }

    /**
     * Sets the value of the fieldIdentities property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setFieldIdentities(ArrayOfString value) {
        this.fieldIdentities = value;
    }

    /**
     * Gets the value of the searchInHistory property.
     * 
     */
    public boolean isSearchInHistory() {
        return searchInHistory;
    }

    /**
     * Sets the value of the searchInHistory property.
     * 
     */
    public void setSearchInHistory(boolean value) {
        this.searchInHistory = value;
    }

    /**
     * Gets the value of the deedStatus property.
     * 
     * @return
     *     possible object is
     *     {@link DeedStatusType }
     *     
     */
    public DeedStatusType getDeedStatus() {
        return deedStatus;
    }

    /**
     * Sets the value of the deedStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeedStatusType }
     *     
     */
    public void setDeedStatus(DeedStatusType value) {
        this.deedStatus = value;
    }

    /**
     * Gets the value of the searchForDeedsType property.
     * 
     * @return
     *     possible object is
     *     {@link SearchForDeedsType }
     *     
     */
    public SearchForDeedsType getSearchForDeedsType() {
        return searchForDeedsType;
    }

    /**
     * Sets the value of the searchForDeedsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchForDeedsType }
     *     
     */
    public void setSearchForDeedsType(SearchForDeedsType value) {
        this.searchForDeedsType = value;
    }

    /**
     * Gets the value of the legalForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalForm() {
        return legalForm;
    }

    /**
     * Sets the value of the legalForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalForm(String value) {
        this.legalForm = value;
    }

}
